//: Playground - noun: a place where people can play

/*
 Problem 1
 If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
 
 Find the sum of all the multiples of 3 or 5 below 1000.
 */
var sum = 0
for i in 1...1000 {
    if i < 1000 {
        if i%3 == 0 || i%5 == 0 {
            sum = sum + i
        }
    }
}
print(sum)


/*
 Problem 2
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
let limit = 4000000
var fibnum = 1, sumEven = 0, prevFibNum = 0
while fibnum < limit {
    if fibnum%2 == 0{
        sumEven = sumEven + fibnum
    }
    var temp = prevFibNum
    prevFibNum = fibnum
    fibnum = fibnum + temp
}
print(sumEven)



